apiVersion: acme.com/v1
kind: Workload
metadata:
  name: app
image: wingcloudbot/kblocks-ui-app:sha-{{ .Values.revision }}
port: 5173
route: /kblocks
replicas: 2
env:
  VITE_SERVER_URL: http://monadahq.com/kblocks/api
  VITE_SERVER_PORT: "80"
command: ["pnpm", "run", "dev"]
