apiVersion: acme.com/v1
kind: Workload
metadata:
  name: kblocks-ui
image: wingcloudbot/kblocks-ui:sha-{{ .Values.revision }}
port: 5175
route: /kblocksui
replicas: 2
env:
  VITE_SERVER_URL: http://localhost
  VITE_SERVER_PORT: "80"
command: ["pnpm", "run", "dev"]