apiVersion: acme.com/v1
kind: Workload
metadata:
  name: kblocks-test-app
image: wingcloudbot/kblocks-test-app:sha-{{ .Values.revision }}
route: /kblocks
replicas: 1
port: 5175
env:
  VITE_SERVER_URL: http://monadahq.com
  VITE_SERVER_PORT: "80"
command: ["npm", "run", "dev"]