apiVersion: acme.com/v1
kind: Workload
metadata:
  name: kblocks-ui
image: wingcloudbot/kblocks-ui-app:sha-{{ .Values.revision }}
port: 5173
route: /kblocks
replicas: 2
env:
  VITE_SERVER_URL: http://monadahq.com
  VITE_SERVER_PORT: "5173"
command: ["pnpm", "run", "dev"]
